export {
  DEPARTMENT,
  DEPARTMENT_IDENTITY_DATA_ENTRY_AUTHORITIES,
  DEPARTMENT_SCOPED_AUTHORITIES,
  EMPLOYEE,
  GLOBAL,
  GLOBAL_IDENTITY_DATA_ENTRY_AUTHORITIES,
  assignRole,
  canPerformAction,
  getUserAuthorities,
  hasAnyAuthority,
  hasAuthority,
  isDepartmentScopedRole,
  normalizeAuthorities,
  resolveScopeAccess,
  resolveUserPermissions,
  revokeRole,
} from "./services/authorizationService";
