export const Permissions = {
  PROFILE_READ_OWN: "PROFILE_READ_OWN",
  PROFILE_READ_ALL: "PROFILE_READ_ALL",
  PROFILE_CREATE: "PROFILE_CREATE",
  PROFILE_UPDATE_OWN_LIMITED: "PROFILE_UPDATE_OWN_LIMITED",
  PROFILE_UPDATE_ALL: "PROFILE_UPDATE_ALL",
  IDENTITY_READ_OWN: "PROFILE_READ_OWN",
  IDENTITY_READ_ALL: "PROFILE_READ_ALL",
  IDENTITY_CREATE: "PROFILE_CREATE",
  IDENTITY_UPDATE_ALL: "PROFILE_UPDATE_ALL",
  SERVICE_BOOK_READ_OWN: "SERVICE_BOOK_READ_OWN",
  SERVICE_BOOK_READ_ALL: "SERVICE_BOOK_READ_ALL",
  SERVICE_BOOK_ENTRY_CREATE: "SERVICE_BOOK_ENTRY_CREATE",
  SERVICE_BOOK_ENTRY_SUBMIT: "SERVICE_BOOK_ENTRY_SUBMIT",
  SERVICE_BOOK_ENTRY_VERIFY: "SERVICE_BOOK_ENTRY_VERIFY",
  SERVICE_BOOK_ENTRY_APPROVE: "SERVICE_BOOK_ENTRY_APPROVE",
  SERVICE_BOOK_ENTRY_ATTEST: "SERVICE_BOOK_ENTRY_ATTEST",
  SERVICE_BOOK_OPENING_CREATE: "SERVICE_BOOK_OPENING_CREATE",
  SERVICE_BOOK_OPENING_UPDATE: "SERVICE_BOOK_OPENING_UPDATE",
  SERVICE_BOOK_OPENING_SUBMIT: "SERVICE_BOOK_OPENING_SUBMIT",
  SERVICE_BOOK_OPENING_VERIFY: "SERVICE_BOOK_OPENING_VERIFY",
  SERVICE_BOOK_OPENING_APPROVE: "SERVICE_BOOK_OPENING_APPROVE",
  SERVICE_BOOK_SUPERSEDE: "SERVICE_BOOK_SUPERSEDE",
  SERVICE_BOOK_PRINT: "SERVICE_BOOK_PRINT",
  LEAVE_APPLY_OWN: "LEAVE_APPLY_OWN",
  LEAVE_READ_OWN: "LEAVE_READ_OWN",
  LEAVE_READ_ALL: "LEAVE_READ_ALL",
  LEAVE_RECOMMEND: "LEAVE_RECOMMEND",
  LEAVE_SANCTION: "LEAVE_SANCTION",
  DOCUMENT_READ_OWN: "DOCUMENT_READ_OWN",
  AUDIT_READ_ALL: "AUDIT_READ_ALL",
  AUDIT_GENERATE_REPORTS: "AUDIT_GENERATE_REPORTS",
  MASTER_READ: "MASTER_READ",
  USER_MANAGEMENT: "USER_MANAGEMENT",
  SYSTEM_CONFIG: "SYSTEM_CONFIG",
};

export const Authorities = {
  EMPLOYEE: "EMPLOYEE",
  DEPT_DATA_ENTRY: "DEPT_DATA_ENTRY",
  GLOBAL_DATA_ENTRY: "GLOBAL_DATA_ENTRY",
  DEALING_ASSISTANT: "DEALING_ASSISTANT",
  SECTION_OFFICER: "SECTION_OFFICER",
  VERIFIER: "VERIFIER",
  NODAL_OFFICER: "NODAL_OFFICER",
  DDO: "DDO",
  APPROVING_AUTHORITY: "APPROVING_AUTHORITY",
  HOD: "HOD",
  APPOINTING_AUTHORITY: "APPOINTING_AUTHORITY",
  DISCIPLINARY_AUTHORITY: "DISCIPLINARY_AUTHORITY",
  AUDITOR: "AUDITOR",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
};

export const WorkflowStages = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  VERIFIED: "VERIFIED",
  APPROVED: "APPROVED",
  LOCKED: "LOCKED",
  SUPERSEDED: "SUPERSEDED",
  REJECTED: "REJECTED",
};

export const EmploymentTypes = {
  REGULAR: "REG",
  CONTRACTUAL: "CON",
  ADHOC: "ADH",
  CASUAL: "CAS",
  OUTSOURCED: "OUT",
  DEPUTATION: "DEP",
  REEMPLOYMENT: "REE",
};

export const normalizeWorkflowStage = (stage) => {
  const normalized = String(stage || "").trim().toUpperCase();
  return normalized === "ATTESTED" ? WorkflowStages.LOCKED : normalized;
};
