"""Employee Master field-level edit and immutability policies.

Canonical merge of:
  - employee_identity.schemas.field_policies.DATA_ENTRY_EDITABLE_FIELDS (identity)
  - employee_profile.schemas.field_policies (extension + ESS + immutable)

Identity and profile editable sets are unioned because employee_master owns both
layers. Values preserved verbatim; nothing removed.
"""

from __future__ import annotations

# Identity-layer fields Data Entry can modify (was employee_identity policy).
IDENTITY_DATA_ENTRY_EDITABLE_FIELDS = {
    "full_name",
    "gender",
    "date_of_birth",
    "current_designation_id",
    "current_office_id",
    "reporting_officer_id",
    "employee_status",
    "status_effective_date",
    "status_remarks",
}

# Profile/engagement fields Data Entry can modify (was employee_profile policy).
PROFILE_EXTENSION_EDITABLE_FIELDS = {
    "employment_type",
    "date_of_initial_engagement",
    "current_department_id",
    "father_name",
    "mother_name",
    "nationality",
    "religion",
    "blood_group",
    "category",
    "sub_caste",
    "date_of_birth_saka",
    "place_of_birth",
    "height_cm",
    "identification_marks",
    "marital_status",
    "spouse_name",
    "educational_qualifications_initial",
    "educational_qualifications_acquired",
    "professional_qualifications",
    "contract_order_no",
    "contract_start_date",
    "contract_end_date",
    "consolidated_pay",
    "contract_authority",
    "vendor_agency",
    "renewal_allowed",
    "engagement_order_no",
    "engagement_order_date",
    "engagement_end_date",
    "remuneration_type",
    "muster_roll_number",
    "daily_wage_rate",
    "wage_rate_unit",
    "engagement_office",
    "nature_of_work",
    "expected_duration_days",
    "fixed_monthly_amount",
    "basic_pay",
    "pay_level",
    "document_ids",
    "engagement_remarks",
    "deputation_order_no",
    "parent_department",
    "parent_designation",
    "lien_status",
    "deputation_start_date",
    "deputation_end_date",
    "deputation_allowance_percent",
    "outsourcing_order_no",
    "agency_name",
    "agency_contract_number",
    "sla_reference",
    "monthly_billing_rate",
    "role_description",
    "mobile_primary",
    "mobile_alternate",
    "email_personal",
    "email_official",
    "address",
    "address_line1",
    "address_line2",
    "city",
    "district",
    "state",
    "pincode",
    "present_address",
    "present_address_line1",
    "present_address_line2",
    "present_city",
    "present_district",
    "present_state",
    "present_pincode",
    "emergency_name",
    "emergency_phone",
    "emergency_relation",
    "aadhaar_number",
    "pan_number",
    "photo_url",
    "signature_url",
    "thumb_impression_url",
    "employee_section_completed",
    "data_entry_section_completed",
    "workflow_remarks",
}

# Union convenience: everything Data Entry may edit across both layers.
DATA_ENTRY_EDITABLE_FIELDS = (
    IDENTITY_DATA_ENTRY_EDITABLE_FIELDS | PROFILE_EXTENSION_EDITABLE_FIELDS
)

# Fields ESS (employee self-service) can modify.
ESS_EDITABLE_FIELDS = {
    "gender",
    "father_name",
    "mother_name",
    "religion",
    "blood_group",
    "category",
    "sub_caste",
    "date_of_birth_saka",
    "place_of_birth",
    "height_cm",
    "identification_marks",
    "marital_status",
    "spouse_name",
    "educational_qualifications_initial",
    "educational_qualifications_acquired",
    "professional_qualifications",
    "mobile_primary",
    "mobile_alternate",
    "email_personal",
    "address",
    "address_line1",
    "address_line2",
    "city",
    "district",
    "state",
    "pincode",
    "present_address",
    "present_address_line1",
    "present_address_line2",
    "present_city",
    "present_district",
    "present_state",
    "present_pincode",
    "emergency_name",
    "emergency_phone",
    "emergency_relation",
    "aadhaar_number",
    "pan_number",
    "photo_url",
    "signature_url",
    "thumb_impression_url",
    "employee_section_completed",
}

# Fields that become immutable after verification.
IMMUTABLE_AFTER_VERIFICATION = {
    "full_name",
    "gender",
    "date_of_birth",
    "date_of_birth_saka",
    "place_of_birth",
    "father_name",
    "mother_name",
    "category",
    "sub_caste",
    "employment_type",
    "date_of_initial_engagement",
    "aadhaar_number",
    "pan_number",
}
