from __future__ import annotations


EMPLOYMENT_TYPE_REGULAR = "REGULAR"
EMPLOYEE_STATUS_ACTIVE = "ACTIVE"
WORKFLOW_STATUS_DRAFT = "DRAFT"
WORKFLOW_STATUS_REJECTED = "REJECTED"
WORKFLOW_STATUS_VERIFIED = "VERIFIED"
WORKFLOW_STATUS_APPROVED = "APPROVED"
WORKFLOW_STATUS_LOCKED = "LOCKED"
