// Fields employees can request changes for — organised by category
export const PROFILE_CATEGORIES = {
  PERSONAL: {
    label: "Personal Details",
    fields: [
      { name: "full_name", label: "Full Name" },
      { name: "father_name", label: "Father's Name" },
      { name: "mother_name", label: "Mother's Name" },
      { name: "date_of_birth", label: "Date of Birth" },
      { name: "gender", label: "Gender" },
      { name: "religion", label: "Religion" },
      { name: "blood_group", label: "Blood Group" },
      { name: "category", label: "Category (SC/ST/OBC/GEN)" },
      { name: "marital_status", label: "Marital Status" },
      { name: "spouse_name", label: "Spouse Name" },
      { name: "nationality", label: "Nationality" },
    ],
  },
  CONTACT: {
    label: "Contact Details",
    fields: [
      { name: "mobile_primary", label: "Mobile Number" },
      { name: "mobile_alternate", label: "Alternate Mobile" },
      { name: "email_personal", label: "Personal Email" },
      { name: "emergency_name", label: "Emergency Contact Name" },
      { name: "emergency_phone", label: "Emergency Contact Phone" },
      { name: "emergency_relation", label: "Emergency Contact Relation" },
    ],
  },
  ADDRESS: {
    label: "Address",
    fields: [
      { name: "address_line1", label: "Address Line 1" },
      { name: "address_line2", label: "Address Line 2" },
      { name: "city", label: "City" },
      { name: "district", label: "District" },
      { name: "state", label: "State" },
      { name: "pincode", label: "PIN Code" },
    ],
  },
  IDENTITY: {
    label: "Identity Documents",
    fields: [
      { name: "aadhaar_number", label: "Aadhaar Number" },
      { name: "pan_number", label: "PAN Number" },
    ],
  },
};

export const SERVICE_BOOK_CATEGORIES = {
  PART_I: {
    label: "Part I \u2014 Bio-Data",
    fields: [
      { name: "name_in_block_letters", label: "Name" },
      { name: "father_name", label: "Father's Name" },
      { name: "mother_name", label: "Mother's Name" },
      { name: "spouse_name", label: "Spouse Name" },
      { name: "marital_status", label: "Marital Status" },
      { name: "nationality", label: "Nationality" },
      { name: "caste_category", label: "Caste Category" },
      { name: "sub_caste", label: "Sub-Caste" },
      { name: "religion", label: "Religion" },
      { name: "date_of_birth_christian", label: "Date of Birth" },
      { name: "date_of_birth_saka", label: "Date of Birth (Saka)" },
      { name: "place_of_birth", label: "Place of Birth" },
      { name: "phone_number", label: "Phone Number" },
      { name: "email", label: "Email" },
      { name: "blood_group", label: "Blood Group" },
      { name: "height_cm", label: "Height (cm)" },
      { name: "identification_marks", label: "Identification Marks" },
      { name: "permanent_address", label: "Permanent Address" },
      { name: "present_address", label: "Present Address" },
      { name: "educational_qualifications_initial", label: "Educational Qualifications (Initial)" },
      { name: "educational_qualifications_acquired", label: "Educational Qualifications (During Service)" },
      { name: "professional_qualifications", label: "Professional Qualifications" },
    ],
  },
  PART_II_A: {
    label: "Part II-A \u2014 Immutable Certificates",
    fields: [
      { name: "medical_fitness_certificate", label: "Medical Fitness Certificate" },
      { name: "medical_exam_date", label: "Medical Exam Date" },
      { name: "medical_officer_name", label: "Medical Officer Name" },
      { name: "medical_category", label: "Medical Category" },
      { name: "character_verification_done", label: "Character Verification" },
      { name: "character_verification_date", label: "Character Verification Date" },
      { name: "character_verification_authority", label: "Character Verification Authority" },
      { name: "police_verification_done", label: "Police Verification" },
      { name: "police_verification_date", label: "Police Verification Date" },
      { name: "oath_of_allegiance_date", label: "Oath of Allegiance Date" },
      { name: "oath_of_secrecy_date", label: "Oath of Secrecy Date" },
      { name: "marital_status_declaration_date", label: "Marital Status Declaration Date" },
      { name: "declared_hometown", label: "Declared Hometown" },
      { name: "hometown_declaration_date", label: "Hometown Declaration Date" },
      { name: "initial_property_return_date", label: "Initial Property Return Date" },
    ],
  },
  PART_II_B: {
    label: "Part II-B \u2014 Mutable Certificates",
    fields: [
      { name: "family_members", label: "Family Sheet" },
      { name: "pcf_account_number", label: "PCF Account Number" },
      { name: "pcf_nomination", label: "PCF Nomination" },
      { name: "dcr_gratuity_nomination", label: "DCR Gratuity Nomination" },
      { name: "family_pension_nomination", label: "Family Pension Nomination" },
      { name: "leave_encashment_nomination", label: "Leave Encashment Nomination" },
      { name: "nps_pran_number", label: "NPS PRAN Number" },
      { name: "nps_nomination", label: "NPS Nomination" },
      { name: "bank_account_number", label: "Bank Account Number" },
      { name: "bank_name", label: "Bank Name" },
      { name: "bank_ifsc", label: "Bank IFSC Code" },
    ],
  },
  PART_III: {
    label: "Part III \u2014 Previous Service",
    entryBased: true,
    fields: [
      { name: "total_previous_qualifying_service", label: "Total Previous Qualifying Service" },
      { name: "verified", label: "Verification Complete" },
      { name: "verified_by", label: "Verified By" },
      { name: "verification_date", label: "Verification Date" },
    ],
    entrySections: [
      {
        key: "previous_services",
        label: "Previous Qualifying Service",
        entryType: "previous_service",
        fields: [
          { name: "post_held", label: "Post Held" },
          { name: "organization", label: "Organisation" },
          { name: "service_from", label: "Service From" },
          { name: "service_to", label: "Service To" },
          { name: "pay_scale", label: "Pay Scale" },
          { name: "purpose_of_qualification", label: "Purpose of Qualification" },
          { name: "qualifying_service_years", label: "Qualifying Service (Years)" },
          { name: "qualifying_service_months", label: "Qualifying Service (Months)" },
          { name: "qualifying_service_days", label: "Qualifying Service (Days)" },
          { name: "remarks", label: "Remarks" },
        ],
      },
      {
        key: "foreign_services",
        label: "Foreign Service (Deputation)",
        entryType: "foreign_service",
        fields: [
          { name: "post_held", label: "Post Held" },
          { name: "employer", label: "Employer" },
          { name: "service_from", label: "Service From" },
          { name: "service_to", label: "Service To" },
          { name: "terms_of_deputation", label: "Terms of Deputation" },
          { name: "remarks", label: "Remarks" },
        ],
      },
    ],
  },
  PART_IV: {
    label: "Part IV \u2014 History of Service",
    entryBased: true,
    entrySections: [
      {
        key: "entries",
        label: "Service History Entry",
        entryType: "service_history",
        fields: [
          { name: "period_from", label: "Period From" },
          { name: "period_to", label: "Period To" },
          { name: "office_station", label: "Office / Station" },
          { name: "post_held", label: "Post Held" },
          { name: "scale_of_pay", label: "Scale of Pay" },
          { name: "pay_band", label: "Pay Band" },
          { name: "grade_pay", label: "Grade Pay" },
          { name: "pay_level", label: "Pay Level" },
          { name: "basic_pay", label: "Basic Pay" },
          { name: "event_type", label: "Event Type" },
          { name: "event_order_number", label: "Event Order Number" },
          { name: "event_order_date", label: "Event Order Date" },
          { name: "remarks", label: "Remarks" },
        ],
      },
    ],
  },
  PART_V: {
    label: "Part V \u2014 Verification",
    entryBased: true,
    entrySections: [
      {
        key: "verification_entries",
        label: "Verification Entry",
        entryType: "verification",
        fields: [
          { name: "period_from", label: "Period From" },
          { name: "period_to", label: "Period To" },
          { name: "post_held", label: "Post Held" },
          { name: "purpose_of_qualification", label: "Purpose of Qualification" },
          { name: "certifying_officer", label: "Certifying Officer" },
          { name: "certification_date", label: "Certification Date" },
          { name: "remarks", label: "Remarks" },
        ],
      },
    ],
  },
  PART_VI: {
    label: "Part VI \u2014 Leave Account",
    entryBased: true,
    fields: [
      { name: "earned_leave_balance", label: "Earned Leave Balance" },
      { name: "half_pay_leave_balance", label: "Half Pay Leave Balance" },
      { name: "commuted_leave_balance", label: "Commuted Leave Balance" },
      { name: "leave_not_due_balance", label: "Leave Not Due Balance" },
    ],
    entrySections: [
      {
        key: "transactions",
        label: "Leave Transaction",
        entryType: "leave_transaction",
        fields: [
          { name: "transaction_type", label: "Transaction Type" },
          { name: "leave_type", label: "Leave Type" },
          { name: "leave_from", label: "Leave From" },
          { name: "leave_to", label: "Leave To" },
          { name: "days_availed", label: "Days Availed" },
          { name: "credit_days", label: "Credit Days" },
          { name: "leave_order_number", label: "Leave Order Number" },
          { name: "leave_order_date", label: "Leave Order Date" },
          { name: "remarks", label: "Remarks" },
        ],
      },
    ],
  },
  PART_VII: {
    label: "Part VII \u2014 Other Records",
    entryBased: true,
    entrySections: [
      {
        key: "ltc_records",
        label: "LTC Record",
        entryType: "ltc",
        fields: [
          { name: "block_year", label: "Block Year" },
          { name: "ltc_type", label: "LTC Type" },
          { name: "journey_from", label: "Journey From" },
          { name: "journey_to", label: "Journey To" },
          { name: "availed_date", label: "Availed Date" },
          { name: "family_members_availed", label: "Family Members Availed" },
          { name: "amount_claimed", label: "Amount Claimed" },
          { name: "amount_sanctioned", label: "Amount Sanctioned" },
        ],
      },
      {
        key: "hba_records",
        label: "HBA Record",
        entryType: "hba",
        fields: [
          { name: "sanction_date", label: "Sanction Date" },
          { name: "amount_sanctioned", label: "Amount Sanctioned" },
          { name: "purpose", label: "Purpose" },
          { name: "property_address", label: "Property Address" },
          { name: "monthly_installment", label: "Monthly Installment" },
          { name: "total_repaid", label: "Total Repaid" },
          { name: "balance_outstanding", label: "Balance Outstanding" },
        ],
      },
    ],
  },
  PART_VIII: {
    label: "Part VIII \u2014 Audit Comments",
    entryBased: true,
    entrySections: [
      {
        key: "comments",
        label: "Audit Comment",
        entryType: "audit_comment",
        fields: [
          { name: "comment_text", label: "Comment Text" },
          { name: "audit_type", label: "Audit Type" },
          { name: "severity", label: "Severity" },
          { name: "part_referred", label: "Part Referred" },
          { name: "response", label: "Response" },
          { name: "resolution", label: "Resolution" },
        ],
      },
    ],
  },
};

// Map category key to service book part key in MongoDB
export const CATEGORY_TO_PART_KEY = {
  PART_I: "I", PART_II_A: "II-A", PART_II_B: "II-B",
  PART_III: "III", PART_IV: "IV", PART_V: "V",
  PART_VI: "VI", PART_VII: "VII", PART_VIII: "VIII",
};

export const PART_KEY_TO_COMPLETE_KEY = {
  I: "part_i",
  "II-A": "part_ii_a",
  "II-B": "part_ii_b",
  III: "part_iii",
  IV: "part_iv",
  V: "part_v",
  VI: "part_vi",
  VII: "part_vii",
  VIII: "part_viii",
};
