from __future__ import annotations

from typing import Protocol

from contexts.leave.contracts.dto import LeaveActionDTO, LeaveApplicationCreateDTO
from app_platform.event_bus.types import BaseEvent


class LeaveGateway(Protocol):
    async def get_leave_balances(self, employee_id: str, *, current_user: dict) -> dict: ...
    async def get_leave_application_policy_context(self, payload: LeaveApplicationCreateDTO, *, current_user: dict) -> dict: ...
    async def apply_leave(self, payload: LeaveApplicationCreateDTO, *, current_user: dict, session=None) -> dict: ...
    async def list_my_leaves(self, *, current_user: dict) -> list[dict]: ...
    async def list_leaves(self, *, status: str | None, leave_type_code: str | None, employee_id: str | None, current_user: dict) -> list[dict]: ...
    async def recommend_leave(self, leave_id: str, action: LeaveActionDTO, *, current_user: dict, session=None) -> dict: ...
    async def sanction_leave(self, leave_id: str, action: LeaveActionDTO, *, current_user: dict, session=None) -> dict: ...
    async def reject_leave(self, leave_id: str, action: LeaveActionDTO, *, current_user: dict, session=None) -> dict: ...
    async def cancel_leave(self, leave_id: str, action: LeaveActionDTO, *, current_user: dict, session=None) -> dict: ...


class LeaveEventSink(Protocol):
    async def publish(self, event: BaseEvent) -> None: ...
