export const partISchema = {
  id: "part_i",
  required: [
    "name_in_block_letters",
    "father_name",
    "marital_status",
    "caste_category",
    "date_of_birth_christian",
  ],
  fields: [
    { name: "employee_id", label: "Employee ID", readOnly: true },
    { name: "employee_code", label: "Employee Code", readOnly: true },
    { name: "name_in_block_letters", label: "Name in Block Letters" },
    { name: "father_name", label: "Father's Name" },
    { name: "mother_name", label: "Mother's Name" },
    { name: "spouse_name", label: "Spouse's Name" },
    { name: "marital_status", label: "Marital Status" },
    { name: "nationality", label: "Nationality" },
    { name: "caste_category", label: "Caste Category" },
    { name: "religion", label: "Religion" },
    { name: "blood_group", label: "Blood Group" },
    { name: "date_of_birth_christian", label: "Date of Birth (Christian era)", type: "date" },
    { name: "place_of_birth", label: "Place of Birth" },
    { name: "height_cm", label: "Exact Height (cm)", type: "number" },
    { name: "identification_marks", label: "Identification Marks", type: "textarea" },
    { name: "permanent_address_line1", label: "Permanent Address Line 1" },
    { name: "permanent_address_line2", label: "Permanent Address Line 2" },
    { name: "educational_qualifications_initial", label: "Educational Qualifications at First Appointment", type: "textarea" },
    { name: "educational_qualifications_acquired", label: "Educational Qualifications Acquired During Service", type: "textarea" },
    { name: "professional_qualifications", label: "Professional / Technical Qualifications", type: "textarea" },
    { name: "attesting_officer_name", label: "Attesting Officer Name" },
    { name: "attesting_officer_designation", label: "Attesting Officer Designation" },
  ],
};
