export const partIIBSchema = {
  id: "part_iib",
  required: [],
  fields: [
    {
      name: "family_members",
      label: "Family Members",
      type: "repeatable_rows",
      addLabel: "Add Family Member",
      emptyState: "No family members added yet.",
      rowLabel: "Family Member",
      fields: [
        { name: "name", label: "Name" },
        { name: "relationship", label: "Relationship" },
        { name: "date_of_birth", label: "Date of Birth", type: "date" },
      ],
    },
    { name: "family_declaration_date", label: "Family Declaration Date", type: "date" },
    { name: "pcf_account_number", label: "PCF Account Number" },
    {
      name: "pcf_nomination",
      label: "PCF Nomination",
      type: "repeatable_rows",
      addLabel: "Add PCF Nominee",
      emptyState: "No PCF nominees added yet.",
      rowLabel: "PCF Nominee",
      fields: [
        { name: "name", label: "Name", type: "select", optionsFromField: "family_members", placeholder: "Select family member", emptyOptionsLabel: "Add a family member first", populateFromSource: { relationship: "relationship" } },
        { name: "relationship", label: "Relationship" },
        { name: "share_percent", label: "Share (%)", type: "number" },
      ],
    },
    { name: "pcf_nomination_date", label: "PCF Nomination Date", type: "date" },
    {
      name: "dcr_gratuity_nomination",
      label: "DCRG Nomination",
      type: "repeatable_rows",
      addLabel: "Add DCRG Nominee",
      emptyState: "No DCRG nominees added yet.",
      rowLabel: "DCRG Nominee",
      fields: [
        { name: "name", label: "Name", type: "select", optionsFromField: "family_members", placeholder: "Select family member", emptyOptionsLabel: "Add a family member first", populateFromSource: { relationship: "relationship" } },
        { name: "relationship", label: "Relationship" },
        { name: "share_percent", label: "Share (%)", type: "number" },
      ],
    },
    { name: "dcr_gratuity_nomination_date", label: "DCRG Nomination Date", type: "date" },
    {
      name: "nps_nomination",
      label: "NPS Nomination",
      type: "repeatable_rows",
      addLabel: "Add NPS Nominee",
      emptyState: "No NPS nominees added yet.",
      rowLabel: "NPS Nominee",
      fields: [
        { name: "name", label: "Name", type: "select", optionsFromField: "family_members", placeholder: "Select family member", emptyOptionsLabel: "Add a family member first", populateFromSource: { relationship: "relationship" } },
        { name: "relationship", label: "Relationship" },
        { name: "share_percent", label: "Share (%)", type: "number" },
      ],
    },
    { name: "nps_nomination_date", label: "NPS Nomination Date", type: "date" },
    {
      name: "leave_encashment_nomination",
      label: "Leave Encashment Nomination",
      type: "repeatable_rows",
      addLabel: "Add Leave Encashment Nominee",
      emptyState: "No leave encashment nominees added yet.",
      rowLabel: "Leave Encashment Nominee",
      fields: [
        { name: "name", label: "Name", type: "select", optionsFromField: "family_members", placeholder: "Select family member", emptyOptionsLabel: "Add a family member first", populateFromSource: { relationship: "relationship" } },
        { name: "relationship", label: "Relationship" },
        { name: "share_percent", label: "Share (%)", type: "number" },
      ],
    },
    { name: "leave_encashment_nomination_date", label: "Leave Encashment Nomination Date", type: "date" },
    {
      name: "family_pension_nomination",
      label: "Family Pension Nomination",
      type: "repeatable_rows",
      addLabel: "Add Family Pension Nominee",
      emptyState: "No family pension nominees added yet.",
      rowLabel: "Family Pension Nominee",
      fields: [
        { name: "name", label: "Name", type: "select", optionsFromField: "family_members", placeholder: "Select family member", emptyOptionsLabel: "Add a family member first", populateFromSource: { relationship: "relationship" } },
        { name: "relationship", label: "Relationship" },
        { name: "share_percent", label: "Share (%)", type: "number" },
      ],
    },
    { name: "family_pension_nomination_date", label: "Family Pension Nomination Date", type: "date" },
    { name: "bank_account_number", label: "Bank Account Number" },
    { name: "bank_name", label: "Bank Name" },
    { name: "bank_ifsc", label: "Bank IFSC" },
    { name: "nps_pran_number", label: "NPS PRAN Number" },
  ],
  sections: [
    {
      id: "family",
      title: "Family",
      description: "Capture the employee's declared family details before recording any nominations.",
      fields: ["family_members", "family_declaration_date"],
    },
    {
      id: "nominations",
      title: "Nominations",
      description: "Record each statutory nomination with its supporting document and effective date.",
      documentUpload: {
        fieldKey: "nominations",
        fieldLabel: "Nominations",
        buttonLabel: "Upload nomination document",
        title: "Nomination Documents",
        description: "Attach the supporting nomination document for the entries recorded in this section.",
      },
      fields: [
        "pcf_account_number",
        "pcf_nomination",
        "pcf_nomination_date",
        "dcr_gratuity_nomination",
        "dcr_gratuity_nomination_date",
        "nps_nomination",
        "nps_nomination_date",
        "leave_encashment_nomination",
        "leave_encashment_nomination_date",
        "family_pension_nomination",
        "family_pension_nomination_date",
      ],
    },
    {
      id: "banking",
      title: "Bank / Account Identifiers",
      description: "Store the account and identifier values that support the recorded nominations.",
      fields: ["bank_account_number", "bank_name", "bank_ifsc", "nps_pran_number"],
    },
  ],
};
