from __future__ import annotations

from typing import Protocol

from contexts.employee_profile.contracts.dto import EmployeeWorkflowAuditDTO, EmployeeWorkflowEventDTO


class EmployeeWorkflowEventGateway(Protocol):
    async def publish(self, *, event_name: str, payload: EmployeeWorkflowEventDTO) -> None: ...

    async def publish_raw(self, *, event_name: str, payload: dict) -> None: ...


class EmployeeProfileWorkflowGateway(Protocol):
    async def persist_transition(
        self,
        *,
        employee_id: str,
        new_status: str,
        remarks: str | None,
        actor_user_id: str,
        transition: str,
    ) -> None: ...


class EmployeeProfileAuditGateway(Protocol):
    async def write_workflow_audit(self, *, payload: EmployeeWorkflowAuditDTO) -> str: ...


class EmployeeProfileRepositoryGateway(Protocol):
    async def get_profile(self, *, employee_id: str) -> dict | None: ...

    async def insert_profile(self, *, profile: dict) -> None: ...

    async def update_profile(self, *, employee_id: str, mongo_update: dict) -> int: ...

    async def archive_and_delete_profile(self, *, profile: dict, actor_user_id: str) -> None: ...

    async def count_profiles(self, *, query: dict) -> int: ...

    async def list_profiles(self, *, query: dict, skip: int = 0, limit: int = 20) -> list[dict]: ...

    async def list_profiles_for_completion(self, *, query: dict, limit: int = 5000) -> list[dict]: ...

    async def list_audit_trail(self, *, employee_id: str, limit: int = 100) -> list[dict]: ...

    async def add_domain_violation_log(self, *, log: dict) -> None: ...

    async def get_user_department_code(self, *, user_id: str) -> str | None: ...

    async def get_profile_department_code(self, *, employee_id: str) -> str | None: ...

    async def get_officer_profile_for_attestation(self, *, employee_id: str) -> dict | None: ...

    async def get_designation_name(self, *, code: str) -> str | None: ...


class EmployeeProfileReadGateway(Protocol):
    async def get_profile(self, *, employee_id: str) -> dict | None: ...

    async def count_profiles(self, *, query: dict) -> int: ...

    async def list_profiles(
        self, *, query: dict, skip: int = 0, limit: int = 20
    ) -> list[dict]: ...
