from __future__ import annotations

from typing import Protocol

from contexts.pay.contracts.dto import AllowanceChangeCreateDTO, PayRevisionCreateDTO


class PayGateway(Protocol):
    async def revise_pay(self, payload: PayRevisionCreateDTO, *, current_user: dict, session=None) -> dict: ...
    async def change_allowance(self, payload: AllowanceChangeCreateDTO, *, current_user: dict, session=None) -> dict: ...
    async def list_ledger_entries(self, employee_id: str, *, current_user: dict) -> list[dict]: ...
    async def get_pay_snapshot(self, employee_id: str, *, current_user: dict) -> dict: ...
