from __future__ import annotations

from typing import Any


ELIGIBILITY_FIELDS = (
    "eligible_for_service_book",
    "eligible_for_seniority",
    "eligible_for_pension",
    "eligible_for_gpf",
    "eligible_for_macp",
    "eligible_for_leave_account",
    "eligible_for_attendance",
    "eligible_for_wages",
    "eligible_for_fixed_remuneration",
)

RETAINED_EMPLOYMENT_TYPE_CODES = (
    "CONTRACT",
    "MUSTER_ROLL",
    "FIXED_PAY",
    "CO_TERMINUS",
    "WAGES",
)


def _master_record(
    *,
    code: str,
    name: str,
    employment_class: str,
    eligible_for_service_book: bool,
    eligible_for_seniority: bool,
    eligible_for_pension: bool,
    eligible_for_gpf: bool,
    eligible_for_macp: bool,
    eligible_for_leave_account: bool,
    eligible_for_attendance: bool,
    eligible_for_wages: bool,
    eligible_for_fixed_remuneration: bool,
    requires_contract_period: bool,
    requires_engagement_order: bool,
) -> dict[str, Any]:
    return {
        "employment_type_code": code,
        "code": code,
        "name": name,
        "employment_class": employment_class,
        "eligible_for_service_book": eligible_for_service_book,
        "eligible_for_seniority": eligible_for_seniority,
        "eligible_for_pension": eligible_for_pension,
        "eligible_for_gpf": eligible_for_gpf,
        "eligible_for_macp": eligible_for_macp,
        "eligible_for_leave_account": eligible_for_leave_account,
        "eligible_for_attendance": eligible_for_attendance,
        "eligible_for_wages": eligible_for_wages,
        "eligible_for_fixed_remuneration": eligible_for_fixed_remuneration,
        "requires_contract_period": requires_contract_period,
        "requires_engagement_order": requires_engagement_order,
        "is_active": True,
    }


EMPLOYMENT_TYPE_MASTER: dict[str, dict[str, Any]] = {
    "REGULAR": _master_record(
        code="REGULAR",
        name="Regular",
        employment_class="REGULAR",
        eligible_for_service_book=True,
        eligible_for_seniority=True,
        eligible_for_pension=True,
        eligible_for_gpf=True,
        eligible_for_macp=True,
        eligible_for_leave_account=True,
        eligible_for_attendance=True,
        eligible_for_wages=False,
        eligible_for_fixed_remuneration=False,
        requires_contract_period=False,
        requires_engagement_order=False,
    ),
    "PROBATIONER": _master_record(
        code="PROBATIONER",
        name="Probationer",
        employment_class="REGULAR",
        eligible_for_service_book=True,
        eligible_for_seniority=True,
        eligible_for_pension=True,
        eligible_for_gpf=True,
        eligible_for_macp=True,
        eligible_for_leave_account=True,
        eligible_for_attendance=True,
        eligible_for_wages=False,
        eligible_for_fixed_remuneration=False,
        requires_contract_period=False,
        requires_engagement_order=False,
    ),
    "TEMPORARY": _master_record(
        code="TEMPORARY",
        name="Temporary",
        employment_class="TEMPORARY",
        eligible_for_service_book=False,
        eligible_for_seniority=False,
        eligible_for_pension=False,
        eligible_for_gpf=False,
        eligible_for_macp=False,
        eligible_for_leave_account=True,
        eligible_for_attendance=True,
        eligible_for_wages=False,
        eligible_for_fixed_remuneration=True,
        requires_contract_period=False,
        requires_engagement_order=True,
    ),
    "MUSTER_ROLL": _master_record(
        code="MUSTER_ROLL",
        name="Muster Roll",
        employment_class="NON_REGULAR",
        eligible_for_service_book=False,
        eligible_for_seniority=False,
        eligible_for_pension=False,
        eligible_for_gpf=False,
        eligible_for_macp=False,
        eligible_for_leave_account=False,
        eligible_for_attendance=True,
        eligible_for_wages=True,
        eligible_for_fixed_remuneration=False,
        requires_contract_period=False,
        requires_engagement_order=True,
    ),
    "CONTRACT": _master_record(
        code="CONTRACT",
        name="Contract",
        employment_class="NON_REGULAR",
        eligible_for_service_book=False,
        eligible_for_seniority=False,
        eligible_for_pension=False,
        eligible_for_gpf=False,
        eligible_for_macp=False,
        eligible_for_leave_account=False,
        eligible_for_attendance=True,
        eligible_for_wages=False,
        eligible_for_fixed_remuneration=True,
        requires_contract_period=True,
        requires_engagement_order=True,
    ),
    "FIXED_PAY": _master_record(
        code="FIXED_PAY",
        name="Fixed Pay",
        employment_class="NON_REGULAR",
        eligible_for_service_book=False,
        eligible_for_seniority=False,
        eligible_for_pension=False,
        eligible_for_gpf=False,
        eligible_for_macp=False,
        eligible_for_leave_account=False,
        eligible_for_attendance=True,
        eligible_for_wages=False,
        eligible_for_fixed_remuneration=True,
        requires_contract_period=False,
        requires_engagement_order=True,
    ),
    "WAGES": _master_record(
        code="WAGES",
        name="Wages",
        employment_class="NON_REGULAR",
        eligible_for_service_book=False,
        eligible_for_seniority=False,
        eligible_for_pension=False,
        eligible_for_gpf=False,
        eligible_for_macp=False,
        eligible_for_leave_account=False,
        eligible_for_attendance=True,
        eligible_for_wages=True,
        eligible_for_fixed_remuneration=False,
        requires_contract_period=False,
        requires_engagement_order=True,
    ),
    "DAILY_RATED": _master_record(
        code="DAILY_RATED",
        name="Daily Rated",
        employment_class="NON_REGULAR",
        eligible_for_service_book=False,
        eligible_for_seniority=False,
        eligible_for_pension=False,
        eligible_for_gpf=False,
        eligible_for_macp=False,
        eligible_for_leave_account=False,
        eligible_for_attendance=True,
        eligible_for_wages=True,
        eligible_for_fixed_remuneration=False,
        requires_contract_period=False,
        requires_engagement_order=True,
    ),
    "CO_TERMINUS": _master_record(
        code="CO_TERMINUS",
        name="Co-Terminus",
        employment_class="NON_REGULAR",
        eligible_for_service_book=False,
        eligible_for_seniority=False,
        eligible_for_pension=False,
        eligible_for_gpf=False,
        eligible_for_macp=False,
        eligible_for_leave_account=False,
        eligible_for_attendance=True,
        eligible_for_wages=False,
        eligible_for_fixed_remuneration=True,
        requires_contract_period=True,
        requires_engagement_order=True,
    ),
    "DEPUTATION": _master_record(
        code="DEPUTATION",
        name="Deputation",
        employment_class="DEPUTATION",
        eligible_for_service_book=False,
        eligible_for_seniority=False,
        eligible_for_pension=True,
        eligible_for_gpf=True,
        eligible_for_macp=False,
        eligible_for_leave_account=True,
        eligible_for_attendance=True,
        eligible_for_wages=False,
        eligible_for_fixed_remuneration=False,
        requires_contract_period=False,
        requires_engagement_order=True,
    ),
    "CASUAL": _master_record(
        code="CASUAL",
        name="Casual",
        employment_class="NON_REGULAR",
        eligible_for_service_book=False,
        eligible_for_seniority=False,
        eligible_for_pension=False,
        eligible_for_gpf=False,
        eligible_for_macp=False,
        eligible_for_leave_account=False,
        eligible_for_attendance=True,
        eligible_for_wages=True,
        eligible_for_fixed_remuneration=False,
        requires_contract_period=False,
        requires_engagement_order=True,
    ),
    "PART_TIME": _master_record(
        code="PART_TIME",
        name="Part Time",
        employment_class="NON_REGULAR",
        eligible_for_service_book=False,
        eligible_for_seniority=False,
        eligible_for_pension=False,
        eligible_for_gpf=False,
        eligible_for_macp=False,
        eligible_for_leave_account=False,
        eligible_for_attendance=True,
        eligible_for_wages=True,
        eligible_for_fixed_remuneration=False,
        requires_contract_period=False,
        requires_engagement_order=True,
    ),
}


ALIASES = {
    "REG": "REGULAR",
    "REGULAR": "REGULAR",
    "PROBATION": "PROBATIONER",
    "PROBATIONER": "PROBATIONER",
    "TEMP": "TEMPORARY",
    "TEMPORARY": "TEMPORARY",
    "MUSTER": "MUSTER_ROLL",
    "MUSTER_ROLL": "MUSTER_ROLL",
    "CON": "CONTRACT",
    "CONTRACT": "CONTRACT",
    "CONTRACTUAL": "CONTRACT",
    "DAILY_WAGE": "DAILY_RATED",
    "DAILYWAGE": "DAILY_RATED",
    "DAILY_RATED": "DAILY_RATED",
    "CAS": "CASUAL",
    "CASUAL": "CASUAL",
    "DEP": "DEPUTATION",
    "DEPUTATION": "DEPUTATION",
    "OUT": "CONTRACT",
    "OUTSOURCED": "CONTRACT",
    "FIXED_PAY": "FIXED_PAY",
    "WAGES": "WAGES",
    "CO_TERMINUS": "CO_TERMINUS",
    "PART_TIME": "PART_TIME",
}


def normalize_employment_type_code(value: Any) -> str | None:
    normalized = str(value or "").strip().upper().replace("-", "_").replace(" ", "_")
    return ALIASES.get(normalized, normalized) if normalized else None


def get_employment_type_master(value: Any) -> dict[str, Any] | None:
    code = normalize_employment_type_code(value)
    if not code:
        return None
    record = EMPLOYMENT_TYPE_MASTER.get(code)
    return dict(record) if record else None


def list_employment_type_master() -> list[dict[str, Any]]:
    return [dict(EMPLOYMENT_TYPE_MASTER[code]) for code in RETAINED_EMPLOYMENT_TYPE_CODES]


def eligibility_from_master(record: dict[str, Any] | None) -> dict[str, bool]:
    source = record or {}
    return {field: bool(source.get(field, False)) for field in ELIGIBILITY_FIELDS}